"""
india_geo.py — Static reference data for Indian states, districts, and major cities.
Used to populate dropdowns in the UI without any external API call.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Data structure:
#   INDIA_GEO = {
#       "State Name": {
#           "District Name": ["City / Town / Tehsil", ...]
#       }
#   }
# ---------------------------------------------------------------------------

INDIA_GEO: dict[str, dict[str, list[str]]] = {
    "Andhra Pradesh": {
        "Visakhapatnam": ["Visakhapatnam", "Bheemunipatnam", "Anakapalle", "Narsipatnam"],
        "East Godavari": ["Kakinada", "Rajahmundry", "Amalapuram"],
        "West Godavari": ["Eluru", "Bhimavaram", "Tanuku"],
        "Krishna": ["Vijayawada", "Machilipatnam", "Gudivada"],
        "Guntur": ["Guntur", "Tenali", "Narasaraopet"],
        "Prakasam": ["Ongole", "Markapur", "Chirala"],
        "Nellore": ["Nellore", "Kavali", "Gudur"],
        "Kurnool": ["Kurnool", "Nandyal", "Adoni"],
        "Kadapa": ["Kadapa", "Proddatur", "Rajampet"],
        "Anantapur": ["Anantapur", "Guntakal", "Hindupur"],
        "Chittoor": ["Tirupati", "Chittoor", "Madanapalle"],
    },
    "Arunachal Pradesh": {
        "East Kameng": ["Seppa"],
        "Papum Pare": ["Itanagar", "Naharlagun"],
        "West Siang": ["Aalo"],
        "Changlang": ["Changlang", "Miao"],
    },
    "Assam": {
        "Kamrup Metropolitan": ["Guwahati", "Dispur"],
        "Kamrup": ["Boko", "Rangia"],
        "Dibrugarh": ["Dibrugarh", "Naharkatia"],
        "Jorhat": ["Jorhat", "Titabar"],
        "Sonitpur": ["Tezpur", "Biswanath Chariali"],
        "Nagaon": ["Nagaon", "Hojai"],
        "Cachar": ["Silchar", "Sonai"],
        "Barpeta": ["Barpeta", "Pathsala"],
        "Dhubri": ["Dhubri", "Bilasipara"],
        "Lakhimpur": ["Lakhimpur", "Dhemaji"],
    },
    "Bihar": {
        "Patna": ["Patna", "Danapur", "Phulwarisharif", "Fatuha"],
        "Gaya": ["Gaya", "Bodh Gaya", "Sherghati"],
        "Muzaffarpur": ["Muzaffarpur", "Motipur"],
        "Bhagalpur": ["Bhagalpur", "Kahalgaon"],
        "Darbhanga": ["Darbhanga", "Benipur"],
        "Purnia": ["Purnia", "Kishanganj"],
        "Begusarai": ["Begusarai", "Barauni"],
        "Munger": ["Munger", "Jamalpur"],
        "Nalanda": ["Bihar Sharif", "Rajgir"],
        "Vaishali": ["Hajipur", "Lalganj"],
    },
    "Chhattisgarh": {
        "Raipur": ["Raipur", "Birgaon", "Arang"],
        "Bilaspur": ["Bilaspur", "Korba"],
        "Durg": ["Durg", "Bhilai", "Rajnandgaon"],
        "Raigarh": ["Raigarh", "Sakti"],
        "Jagdalpur": ["Jagdalpur"],
        "Ambikapur": ["Ambikapur", "Manendragarh"],
    },
    "Goa": {
        "North Goa": ["Panaji", "Mapusa", "Pernem", "Calangute"],
        "South Goa": ["Margao", "Vasco da Gama", "Ponda"],
    },
    "Gujarat": {
        "Ahmedabad": ["Ahmedabad", "Gandhinagar", "Sanand", "Dholka"],
        "Surat": ["Surat", "Bardoli", "Navsari"],
        "Vadodara": ["Vadodara", "Anand", "Karjan"],
        "Rajkot": ["Rajkot", "Morbi", "Gondal"],
        "Bhavnagar": ["Bhavnagar", "Botad", "Sihor"],
        "Jamnagar": ["Jamnagar", "Dwarka", "Khambhalia"],
        "Junagadh": ["Junagadh", "Porbandar", "Veraval"],
        "Kutch": ["Bhuj", "Gandhidham", "Mandvi"],
        "Mehsana": ["Mehsana", "Unjha", "Visnagar"],
        "Gandhinagar": ["Gandhinagar", "Mansa"],
        "Patan": ["Patan", "Siddhpur"],
        "Banaskantha": ["Palanpur", "Deesa"],
    },
    "Haryana": {
        "Gurugram": ["Gurugram", "Manesar", "Sohna"],
        "Faridabad": ["Faridabad", "Ballabhgarh"],
        "Ambala": ["Ambala", "Ambala City", "Naraingarh"],
        "Karnal": ["Karnal", "Panipat", "Assandh"],
        "Hisar": ["Hisar", "Hansi", "Fatehabad"],
        "Rohtak": ["Rohtak", "Jhajjar"],
        "Sonipat": ["Sonipat", "Gohana", "Kundli"],
        "Kurukshetra": ["Kurukshetra", "Thanesar"],
        "Yamunanagar": ["Yamunanagar", "Jagadhri"],
        "Sirsa": ["Sirsa", "Ellenabad"],
        "Bhiwani": ["Bhiwani", "Loharu"],
        "Rewari": ["Rewari", "Dharuhera"],
        "Mahendragarh": ["Narnaul", "Mahendragarh"],
        "Panchkula": ["Panchkula", "Kalka"],
    },
    "Himachal Pradesh": {
        "Shimla": ["Shimla", "Solan", "Parwanoo"],
        "Kangra": ["Dharamsala", "Palampur", "Nurpur"],
        "Mandi": ["Mandi", "Sundarnagar"],
        "Kullu": ["Kullu", "Manali"],
        "Hamirpur": ["Hamirpur", "Barsar"],
        "Una": ["Una", "Amb"],
        "Chamba": ["Chamba", "Dalhousie"],
        "Bilaspur": ["Bilaspur"],
        "Sirmaur": ["Nahan", "Paonta Sahib"],
        "Solan": ["Solan", "Baddi", "Nalagarh"],
    },
    "Jharkhand": {
        "Ranchi": ["Ranchi", "Hatia", "Namkum"],
        "Dhanbad": ["Dhanbad", "Jharia", "Sindri"],
        "Jamshedpur": ["Jamshedpur", "Jugsalai"],
        "Bokaro": ["Bokaro Steel City", "Chas"],
        "Hazaribagh": ["Hazaribagh", "Ramgarh"],
        "Deoghar": ["Deoghar", "Jasidih"],
        "Giridih": ["Giridih"],
        "Dumka": ["Dumka"],
    },
    "Karnataka": {
        "Bengaluru Urban": ["Bengaluru", "Yelahanka", "Whitefield", "Electronic City", "Jayanagar"],
        "Bengaluru Rural": ["Nelamangala", "Doddaballapur", "Hoskote"],
        "Mysuru": ["Mysuru", "Mandya", "Srirangapatna"],
        "Hubballi-Dharwad": ["Hubballi", "Dharwad"],
        "Belagavi": ["Belagavi", "Gokak", "Bagalkot"],
        "Kalaburagi": ["Kalaburagi", "Shahabad", "Sedam"],
        "Mangaluru": ["Mangaluru", "Puttur", "Bantwal"],
        "Shivamogga": ["Shivamogga", "Bhadravati", "Sagara"],
        "Ballari": ["Ballari", "Hospet", "Sandur"],
        "Vijayapura": ["Vijayapura", "Muddebihal"],
        "Tumakuru": ["Tumakuru", "Madhugiri", "Tiptur"],
        "Hassan": ["Hassan", "Arsikere", "Belur"],
        "Chikkamagaluru": ["Chikkamagaluru", "Kadur", "Tarikere"],
        "Raichur": ["Raichur", "Sindhanur", "Manvi"],
        "Koppal": ["Koppal", "Gangavathi"],
        "Davanagere": ["Davanagere", "Harihara", "Harihar"],
        "Chitradurga": ["Chitradurga", "Challakere"],
        "Kolar": ["Kolar", "KGF", "Bangarpet"],
        "Chikkaballapur": ["Chikkaballapur", "Gauribidanur"],
        "Yadgir": ["Yadgir", "Shorapur"],
        "Gadag": ["Gadag", "Betgeri", "Ron"],
        "Haveri": ["Haveri", "Savanur", "Byadagi"],
        "Kodagu": ["Madikeri", "Virajpet"],
        "Chamarajanagar": ["Chamarajanagar", "Gundlupet"],
        "Mandya": ["Mandya", "Srirangapatna", "Maddur"],
        "Ramanagara": ["Ramanagara", "Channapatna"],
        "Udupi": ["Udupi", "Manipal", "Kundapura"],
        "Dharwad": ["Dharwad"],
    },
    "Kerala": {
        "Thiruvananthapuram": ["Thiruvananthapuram", "Attingal", "Neyyattinkara"],
        "Kollam": ["Kollam", "Punalur", "Kottarakkara"],
        "Pathanamthitta": ["Pathanamthitta", "Tiruvalla"],
        "Alappuzha": ["Alappuzha", "Chengannur", "Kayamkulam"],
        "Kottayam": ["Kottayam", "Changanacherry", "Ettumanoor"],
        "Idukki": ["Idukki", "Munnar", "Thodupuzha"],
        "Ernakulam": ["Ernakulam", "Kochi", "Thrippunithura", "Aluva"],
        "Thrissur": ["Thrissur", "Chalakudy", "Irinjalakuda"],
        "Palakkad": ["Palakkad", "Ottappalam", "Mannarkkad"],
        "Malappuram": ["Malappuram", "Manjeri", "Tirur"],
        "Kozhikode": ["Kozhikode", "Vadakara", "Koyilandy"],
        "Wayanad": ["Kalpetta", "Mananthavady"],
        "Kannur": ["Kannur", "Thalassery", "Payyanur"],
        "Kasaragod": ["Kasaragod", "Kanhangad"],
    },
    "Madhya Pradesh": {
        "Bhopal": ["Bhopal", "Berasia", "Mandideep"],
        "Indore": ["Indore", "Dewas", "Pithampur"],
        "Jabalpur": ["Jabalpur", "Katni", "Bargi"],
        "Gwalior": ["Gwalior", "Morar", "Gwalior City"],
        "Ujjain": ["Ujjain", "Nagda", "Maksi"],
        "Sagar": ["Sagar", "Bina", "Khurai"],
        "Rewa": ["Rewa", "Satna", "Maihar"],
        "Dhar": ["Dhar", "Mhow", "Pithampur"],
        "Morena": ["Morena", "Ambah", "Porsa"],
        "Ratlam": ["Ratlam", "Jaora", "Sailana"],
        "Shivpuri": ["Shivpuri", "Guna"],
        "Chhindwara": ["Chhindwara", "Seoni"],
        "Hoshangabad": ["Hoshangabad", "Itarsi", "Pipariya"],
        "Mandsaur": ["Mandsaur", "Neemuch", "Garoth"],
        "Vidisha": ["Vidisha", "Ganjbasoda"],
        "Raisen": ["Raisen", "Obaidullaganj"],
        "Tikamgarh": ["Tikamgarh", "Niwari"],
    },
    "Maharashtra": {
        "Mumbai City": ["Mumbai", "Colaba", "Bandra", "Andheri", "Borivali"],
        "Mumbai Suburban": ["Thane", "Kurla", "Kandivali", "Malad"],
        "Pune": ["Pune", "Pimpri-Chinchwad", "Hadapsar", "Kothrud"],
        "Nagpur": ["Nagpur", "Kamptee", "Butibori"],
        "Nashik": ["Nashik", "Ozar", "Igatpuri"],
        "Aurangabad": ["Aurangabad", "Paithan", "Gangapur"],
        "Solapur": ["Solapur", "Barshi", "Akkalkot"],
        "Amravati": ["Amravati", "Achalpur", "Daryapur"],
        "Kolhapur": ["Kolhapur", "Ichalkaranji", "Hatkanangle"],
        "Satara": ["Satara", "Karad", "Wai"],
        "Sangli": ["Sangli", "Miraj", "Islampur"],
        "Jalgaon": ["Jalgaon", "Bhusawal", "Amalner"],
        "Akola": ["Akola", "Murtizapur"],
        "Nanded": ["Nanded", "Biloli", "Degloor"],
        "Latur": ["Latur", "Osmanabad"],
        "Chandrapur": ["Chandrapur", "Ballarpur"],
        "Yavatmal": ["Yavatmal", "Wani"],
        "Beed": ["Beed", "Ambejogai"],
        "Osmanabad": ["Osmanabad"],
        "Raigad": ["Alibag", "Pen", "Panvel"],
        "Thane": ["Thane", "Kalyan", "Ulhasnagar", "Bhiwandi", "Navi Mumbai"],
        "Palghar": ["Palghar", "Vasai", "Virar", "Boisar"],
    },
    "Manipur": {
        "Imphal West": ["Imphal", "Lamphelpat"],
        "Imphal East": ["Porompat", "Mayang Imphal"],
        "Bishnupur": ["Bishnupur", "Moirang"],
        "Thoubal": ["Thoubal", "Kakching"],
    },
    "Meghalaya": {
        "East Khasi Hills": ["Shillong", "Cherrapunji", "Mairang"],
        "West Khasi Hills": ["Nongstoin"],
        "Ri Bhoi": ["Nongpoh"],
        "Jaintia Hills": ["Jowai", "Khliehriat"],
        "West Garo Hills": ["Tura", "Dalu"],
        "East Garo Hills": ["Williamnagar"],
    },
    "Mizoram": {
        "Aizawl": ["Aizawl", "Durtlang"],
        "Lunglei": ["Lunglei"],
        "Champhai": ["Champhai"],
        "Kolasib": ["Kolasib"],
    },
    "Nagaland": {
        "Kohima": ["Kohima", "Zubza"],
        "Dimapur": ["Dimapur", "Chumukedima"],
        "Mokokchung": ["Mokokchung"],
        "Wokha": ["Wokha"],
    },
    "Odisha": {
        "Khordha": ["Bhubaneswar", "Puri", "Khordha"],
        "Cuttack": ["Cuttack", "Choudwar", "Athagarh"],
        "Ganjam": ["Berhampur", "Bhanjanagar", "Chatrapur"],
        "Sambalpur": ["Sambalpur", "Burla", "Hirakud"],
        "Sundargarh": ["Sundargarh", "Rourkela"],
        "Balasore": ["Balasore", "Jaleswar", "Nilagiri"],
        "Mayurbhanj": ["Baripada", "Rairangpur"],
        "Kendrapara": ["Kendrapara", "Jagatsinghpur"],
        "Koraput": ["Koraput", "Jeypore"],
        "Rayagada": ["Rayagada"],
    },
    "Punjab": {
        "Ludhiana": ["Ludhiana", "Jagraon", "Khanna"],
        "Amritsar": ["Amritsar", "Tarn Taran", "Ajnala"],
        "Jalandhar": ["Jalandhar", "Phagwara", "Nakodar"],
        "Patiala": ["Patiala", "Rajpura", "Nabha"],
        "Mohali": ["Mohali", "Kharar", "Derabassi"],
        "Bathinda": ["Bathinda", "Mansa", "Rampura Phul"],
        "Firozpur": ["Firozpur", "Ferozepur Cantonment"],
        "Gurdaspur": ["Gurdaspur", "Pathankot", "Batala"],
        "Hoshiarpur": ["Hoshiarpur", "Mukerian"],
        "Sangrur": ["Sangrur", "Sunam", "Malerkotla"],
        "Fatehgarh Sahib": ["Fatehgarh Sahib", "Sirhind"],
        "Moga": ["Moga", "Baghapurana"],
        "Fazilka": ["Fazilka", "Abohar"],
        "Ropar": ["Ropar", "Morinda"],
        "Nawanshahr": ["Nawanshahr", "Balachaur"],
        "Muktsar": ["Muktsar"],
        "Kapurthala": ["Kapurthala", "Phagwara"],
    },
    "Rajasthan": {
        "Jaipur": ["Jaipur", "Sanganer", "Bagru", "Amber"],
        "Jodhpur": ["Jodhpur", "Phalodi", "Osian"],
        "Udaipur": ["Udaipur", "Nathdwara", "Rajsamand"],
        "Kota": ["Kota", "Baran", "Bundi"],
        "Ajmer": ["Ajmer", "Pushkar", "Kishangarh"],
        "Bikaner": ["Bikaner", "Nokha", "Lunkaransar"],
        "Alwar": ["Alwar", "Bhiwadi", "Behror"],
        "Bhilwara": ["Bhilwara", "Shahpura"],
        "Sikar": ["Sikar", "Fatehpur"],
        "Sri Ganganagar": ["Sri Ganganagar", "Suratgarh", "Anupgarh"],
        "Hanumangarh": ["Hanumangarh", "Tibi"],
        "Barmer": ["Barmer", "Balotra"],
        "Jaisalmer": ["Jaisalmer", "Sam"],
        "Pali": ["Pali", "Sojat"],
        "Nagaur": ["Nagaur", "Didwana"],
        "Jhunjhunu": ["Jhunjhunu", "Chirawa", "Pilani"],
        "Churu": ["Churu", "Ratangarh", "Sardarshahar"],
        "Tonk": ["Tonk", "Deoli"],
        "Sawai Madhopur": ["Sawai Madhopur", "Gangapur City"],
        "Dausa": ["Dausa", "Lalsot"],
    },
    "Sikkim": {
        "East Sikkim": ["Gangtok", "Rangpo"],
        "West Sikkim": ["Gyalshing", "Soreng"],
        "North Sikkim": ["Mangan"],
        "South Sikkim": ["Namchi", "Jorethang"],
    },
    "Tamil Nadu": {
        "Chennai": ["Chennai", "Ambattur", "Avadi", "Sholinganallur", "Perambur"],
        "Coimbatore": ["Coimbatore", "Tirupur", "Pollachi"],
        "Madurai": ["Madurai", "Usilampatti", "Melur"],
        "Salem": ["Salem", "Mettur", "Omalur"],
        "Tiruchirappalli": ["Tiruchirappalli", "Srirangam", "Lalgudi"],
        "Tirunelveli": ["Tirunelveli", "Palayamkottai", "Tenkasi"],
        "Vellore": ["Vellore", "Katpadi", "Ambur"],
        "Erode": ["Erode", "Tiruppur", "Bhavani"],
        "Thanjavur": ["Thanjavur", "Kumbakonam", "Papanasam"],
        "Cuddalore": ["Cuddalore", "Panruti"],
        "Nagapattinam": ["Nagapattinam", "Mayiladuthurai"],
        "Dindigul": ["Dindigul", "Palani", "Vedasandur"],
        "Kancheepuram": ["Kancheepuram", "Sriperumbudur"],
        "Chengalpattu": ["Chengalpattu", "Tambaram"],
        "Krishnagiri": ["Krishnagiri", "Hosur"],
        "Dharmapuri": ["Dharmapuri", "Palacode"],
        "The Nilgiris": ["Ooty", "Coonoor", "Kotagiri"],
        "Ramanathapuram": ["Ramanathapuram", "Paramakudi"],
        "Thoothukudi": ["Thoothukudi", "Kovilpatti"],
        "Kanniyakumari": ["Nagercoil", "Marthandam"],
        "Virudhunagar": ["Virudhunagar", "Sivakasi", "Rajapalayam"],
        "Karur": ["Karur", "Kulithalai"],
        "Villupuram": ["Villupuram", "Tindivanam"],
        "Perambalur": ["Perambalur"],
        "Ariyalur": ["Ariyalur"],
        "Ranipet": ["Ranipet", "Walajapet"],
        "Tirupathur": ["Tirupathur", "Vaniyambadi"],
    },
    "Telangana": {
        "Hyderabad": ["Hyderabad", "Secunderabad", "Banjara Hills", "Jubilee Hills", "HITEC City", "Gachibowli"],
        "Rangareddy": ["Rangareddy", "LB Nagar", "Kukatpally", "Shamshabad", "Maheshwaram"],
        "Medchal-Malkajgiri": ["Medchal", "Kompally", "Secunderabad Cantonment"],
        "Warangal Urban": ["Warangal", "Kazipet", "Hanamkonda"],
        "Khammam": ["Khammam", "Kothagudem", "Wyra"],
        "Nalgonda": ["Nalgonda", "Miryalaguda", "Suryapet"],
        "Nizamabad": ["Nizamabad", "Armoor", "Bodhan"],
        "Karimnagar": ["Karimnagar", "Jammikunta", "Huzurabad"],
        "Mahbubnagar": ["Mahbubnagar", "Wanaparthy"],
        "Adilabad": ["Adilabad", "Nirmal", "Mancherial"],
        "Siddipet": ["Siddipet", "Gajwel"],
        "Sangareddy": ["Sangareddy", "Patancheru"],
    },
    "Tripura": {
        "West Tripura": ["Agartala", "Bishalgarh"],
        "South Tripura": ["Belonia", "Sabroom"],
        "North Tripura": ["Dharmanagar", "Kumarghat"],
        "Gomati": ["Udaipur"],
    },
    "Uttar Pradesh": {
        "Lucknow": ["Lucknow", "Gomti Nagar", "Hazratganj", "Aliganj"],
        "Agra": ["Agra", "Mathura", "Firozabad"],
        "Varanasi": ["Varanasi", "Sarnath", "Chandauli"],
        "Kanpur": ["Kanpur", "Unnao", "Kanpur Dehat"],
        "Allahabad": ["Prayagraj", "Phulpur", "Meja"],
        "Meerut": ["Meerut", "Hapur", "Bagpat"],
        "Ghaziabad": ["Ghaziabad", "Noida", "Greater Noida", "Indirapuram"],
        "Gautam Buddha Nagar": ["Noida", "Greater Noida", "Dadri"],
        "Bareilly": ["Bareilly", "Pilibhit", "Shahjahanpur"],
        "Moradabad": ["Moradabad", "Sambhal", "Rampur"],
        "Aligarh": ["Aligarh", "Hathras", "Iglas"],
        "Gorakhpur": ["Gorakhpur", "Deoria", "Basti"],
        "Muzaffarnagar": ["Muzaffarnagar", "Shamli", "Kairana"],
        "Saharanpur": ["Saharanpur", "Deoband", "Rampur Maniharan"],
        "Jhansi": ["Jhansi", "Lalitpur", "Datia"],
        "Banda": ["Banda", "Chitrakoot", "Hamirpur"],
        "Bijnor": ["Bijnor", "Nagina"],
        "Bulandshahr": ["Bulandshahr", "Khurja", "Sikandrabad"],
        "Etah": ["Etah", "Kasganj"],
        "Farrukhabad": ["Farrukhabad", "Fatehgarh"],
        "Gonda": ["Gonda", "Balrampur"],
        "Hardoi": ["Hardoi", "Shahabad"],
        "Jaunpur": ["Jaunpur", "Mungra Badshahpur"],
        "Mirzapur": ["Mirzapur", "Vindhyachal"],
        "Sitapur": ["Sitapur", "Mahmudabad"],
        "Sultanpur": ["Sultanpur", "Musafirkhana"],
        "Azamgarh": ["Azamgarh", "Lalganj"],
        "Etawah": ["Etawah", "Jaswantnagar"],
        "Mainpuri": ["Mainpuri", "Shikohabad"],
        "Pratapgarh": ["Pratapgarh", "Lalganj"],
        "Rae Bareli": ["Rae Bareli", "Lalganj"],
        "Balia": ["Ballia", "Rasra"],
    },
    "Uttarakhand": {
        "Dehradun": ["Dehradun", "Rishikesh", "Mussoorie", "Haridwar"],
        "Haridwar": ["Haridwar", "Roorkee", "Jwalapur"],
        "Nainital": ["Nainital", "Haldwani", "Ramnagar"],
        "Udham Singh Nagar": ["Rudrapur", "Kashipur", "Bazpur"],
        "Almora": ["Almora", "Ranikhet"],
        "Pauri Garhwal": ["Pauri", "Kotdwar", "Lansdowne"],
        "Tehri Garhwal": ["Tehri", "Chamba", "Devprayag"],
        "Chamoli": ["Gopeshwar", "Joshimath", "Karnaprayag"],
        "Pithoragarh": ["Pithoragarh", "Dharchula"],
        "Bageshwar": ["Bageshwar", "Kanda"],
        "Champawat": ["Champawat", "Lohaghat"],
        "Rudraprayag": ["Rudraprayag", "Ukhimath"],
        "Uttarkashi": ["Uttarkashi", "Barkot"],
    },
    "West Bengal": {
        "Kolkata": ["Kolkata", "Howrah", "Salt Lake City", "Dum Dum", "Barasat"],
        "North 24 Parganas": ["Barasat", "Barackpore", "Habra", "Bongaon"],
        "South 24 Parganas": ["Diamond Harbour", "Budge Budge", "Bishnupur"],
        "Hooghly": ["Hooghly", "Serampore", "Chinsurah", "Uttarpara"],
        "Howrah": ["Howrah", "Uluberia", "Jagachha"],
        "Paschim Medinipur": ["Midnapore", "Kharagpur", "Jhargram"],
        "Purba Medinipur": ["Contai", "Haldia", "Tamluk"],
        "Murshidabad": ["Berhampore", "Jangipur", "Dhulian"],
        "Nadia": ["Krishnanagar", "Nabadwip", "Kalyani"],
        "Burdwan": ["Asansol", "Durgapur", "Burdwan"],
        "Birbhum": ["Suri", "Bolpur", "Rampurhat"],
        "Bankura": ["Bankura", "Bishnupur"],
        "Purulia": ["Purulia", "Raghunathpur"],
        "Jalpaiguri": ["Jalpaiguri", "Siliguri", "Alipurduar"],
        "Darjeeling": ["Darjeeling", "Kurseong", "Kalimpong"],
        "Malda": ["Malda", "English Bazar", "Gajole"],
        "North Dinajpur": ["Raiganj", "Islampur"],
        "South Dinajpur": ["Balurghat", "Gangarampur"],
        "Cooch Behar": ["Cooch Behar", "Mathabhanga"],
    },
    "Delhi": {
        "New Delhi": ["New Delhi", "Connaught Place", "Karol Bagh"],
        "Central Delhi": ["Chandni Chowk", "Paharganj"],
        "North Delhi": ["Civil Lines", "Burari", "Alipur"],
        "North East Delhi": ["Seelampur", "Mustafabad", "Yamuna Vihar"],
        "East Delhi": ["Preet Vihar", "Laxmi Nagar", "Vivek Vihar"],
        "New Delhi": ["Saket", "Lajpat Nagar", "Kalkaji"],
        "South Delhi": ["Hauz Khas", "Greater Kailash", "Vasant Kunj", "Malviya Nagar"],
        "South West Delhi": ["Dwarka", "Palam", "Uttam Nagar"],
        "West Delhi": ["Janakpuri", "Tilak Nagar", "Rajouri Garden"],
        "North West Delhi": ["Pitampura", "Shalimar Bagh", "Rohini"],
        "Shahdara": ["Shahdara", "Seema Puri"],
        "Outer Delhi": ["Mundka", "Bawana", "Narela"],
    },
    "Jammu and Kashmir": {
        "Srinagar": ["Srinagar", "Ganderbal", "Budgam"],
        "Jammu": ["Jammu", "Kathua", "Samba"],
        "Baramulla": ["Baramulla", "Sopore"],
        "Anantnag": ["Anantnag", "Bijbehara"],
        "Kupwara": ["Kupwara", "Handwara"],
        "Poonch": ["Poonch", "Surankote"],
        "Rajouri": ["Rajouri", "Nowshera"],
    },
    "Ladakh": {
        "Leh": ["Leh", "Nubra"],
        "Kargil": ["Kargil", "Zanskar"],
    },
    "Puducherry": {
        "Puducherry": ["Puducherry", "Oulgaret", "Villianur"],
        "Karaikal": ["Karaikal"],
        "Mahe": ["Mahe"],
        "Yanam": ["Yanam"],
    },
    "Chandigarh": {
        "Chandigarh": ["Chandigarh", "Manimajra", "Industrial Area"],
    },
}


def get_states() -> list[str]:
    """Return sorted list of all states/UTs."""
    return sorted(INDIA_GEO.keys())


def get_districts(state: str) -> list[str]:
    """Return sorted list of districts for a given state."""
    return sorted(INDIA_GEO.get(state, {}).keys())


def get_cities(state: str, district: str) -> list[str]:
    """Return list of cities/towns for a given state and district."""
    return INDIA_GEO.get(state, {}).get(district, [])
